### ISSUE TITLE
Capture system for L5

### ISSUE THREAD

**Issue by Lilyo** [zju3dv/deltar#10]
Hi ,
Thanks for the great work! I'm curious how to access the histogram data from the L5 sensor? I really appreciate you can share your capture system:)

Regards.

**Comment by eugenelyj** [comment]
@Lilyo Unfortunately, the raw histogram data is not accessible and we can only access to the mean and variance due to the band limit (see the supplementary material for details). As for the capture system, please refer to the paper. If you are looking for the calibration code, we release it in this this [repo](https://github.com/eugenelyj/Calib_DELTAR).
