### ISSUE TITLE
Interpolation for solving misalignment

### ISSUE THREAD

**Issue by sunyuan789** [zju3dv/deltar#3]
How did you do on Interpolation for solving misalignment? Could you please describe some more details or some code snippets?

**Comment by eugenelyj** [comment]
@sunyuan789 Hi, the process is a bit complex. 

First i will fit a comact rectangle on the zones and dividing the rectangle into equal-sized blocks (for this step you can see Fig.C and related paragraph in the supp.). The equal-sized blocks/zones are convenient for batch processing. 

Second, if the rectangle can not be evenly divisible by the number of blocks/zones (which means the patch width/height is Float instead of Int), i will interpolate to make them evenly divisible (see Fig.6 in the paper).

Take a 1d example. I have a 1d feature with shape [10] and 6 zones covering the feature. Then i will interpolate the feature to the shapw [12] such that each zone cover feature with 2 pixels. The interpolation is simply implemented by bilinear interpolation.
